- name: install chirpstack-network-server
  package:
    name: chirpstack-network-server
    state: latest

- name: copy configuration
  template:
    src: chirpstack-network-server.toml
    dest: /etc/chirpstack-network-server/chirpstack-network-server.toml
    owner: networkserver
    group: networkserver
    mode: "0640"
  notify:
    - restart chirpstack-network-server

- name: start chirpstack-network-server on boot
  service:
    name: chirpstack-network-server
    state: started
    enabled: yes
